site_name: A specification for cryo-ET metadata
site_url: https://cryo-et-standards.github.io/cryoet-geometry
site_author: bla
site_description: >-
  A specification for cryo-ET metadata
repo_name: cryo-et-standards/cryoet-geometry
repo_url: https://github.com/cryo-et-standards/cryoet-geometry
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2022 - 2024 cryo-et-standards WG


# Custom navigation can be specified
nav:
  - Overview: index.md
  - Geometry Definitions: geometry/geometry_metadata.md
  - LinkML Models: linkml/index.md

theme:
  icon:
    logo: material/cube-outline
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue

  features:
    - navigation.instant
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.tabs.link

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js